### ISSUE TITLE
Suggestion: check if gravatar exists

### ISSUE THREAD

**Issue by eneroth** [dator-zz/sfGravatarPlugin#1]
It would be really useful if the plugin could indicate if the email has an associated avatar. A solution I've found for this is to check the HTTP header of the sfGravatar generated URL, like so:
    function getHttpResponse($theURL) {
      $headers = get_headers($theURL);
      return substr($headers[0], 9, 3);
    }

```
function hasGravatar($email, $rating = 'g') {
  return (getHttpResponse(gravatar_image($email, 80, $rating, '404')) == '200');
}
```

**Comment by dator-zz** [comment]
Why do this ?

Gravatar detect himself if the user as a gravatar, if not, the api return a default avatar :)

**Comment by eneroth** [comment]
Well, let's say you want to encourage the user to set up a Gravatar if no one exists. Then you could do the following:
in action.class.php:
    $this->email = $this->getUser()->getProfile()->email;
    $this->hasGravatar = Gravatar::hasGravatar($this->email, 'G');

in success template:
    <?php if($hasGravatar): ?>
        <?php echo gravatar_image_tag($email) ?>
    <?php else: ?>
        <p>You don't seem to have a Gravatar set up!<p>
        <p>Set one up at <?php echo link_to('Gravatar', 'http://www.gravatar.com') ?>
    <?php endif; ?>

**Comment by dator-zz** [comment]
By the way, i try your code, it seems to slow the page ... 700ms with, 100ms without .. 
Any idea ?

**Comment by eneroth** [comment]
Yeah, the thief is the get_headers function. Standard PHP library, but it seems slow. I just picked it to illustrate the idea - there's probably a better way to do it.

**Comment by eneroth** [comment]
Thanks for including the suggestion! :-)

I tried a cURL method of checking. It seems to be quite a bit faster:
    private function urlExists($url) {
      $ch = curl_init();
      curl_setopt($ch, CURLOPT_URL,$url);
      // don't download content
      curl_setopt($ch, CURLOPT_NOBODY, 1);
      curl_setopt($ch, CURLOPT_FAILONERROR, 1);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

```
  if(curl_exec($ch)!==FALSE)
  {
      return true;
  }
  else
  {
      return false;
  }
}

private function checkForGravatar($rating = 'G') {
    sfProjectConfiguration::getActive()->loadHelpers(array("Gravatar"));
    $url      = gravatar_image($this->email, 80, $rating, '404');

    return self::urlExists($url);
}
```

**Comment by dator-zz** [comment]
Commit ;) Less slow but still a little slow but good  anyway ;)
